assert taggable beforing tagging.

diff --git a/Makefile.maint b/Makefile.maint
--- a/Makefile.maint
+++ b/Makefile.maint
@@ -13,8 +13,13 @@ gh-pages: html
 	ghp-import -p -f html
 
 tag:
-	@git tag $(VERSION);
-	git tag
+	@if git describe --always --dirty --abbrev=10 | grep dirty ; then \
+	    echo "FAILED: version not clean, cannot tag a release." ; exit 1; \
+	else \
+	    git tag $(VERSION); \
+	    echo "Current list of tags : "; \
+	    git tag; \
+	fi;
 
 sdist:
 	bash maintainer/git-archive-all.sh --prefix MPGadget-$(VERSION)/ -- - | gzip -c > MPGadget-$(VERSION).tar.gz
